name: cadquery
channels:
  - cadquery
  - conda-forge
  - defaults
dependencies:
  - python>=3.6
  - ipython
  - ocp=7.5
  - pyparsing
  - sphinx=3.2.1
  - sphinx_rtd_theme
  - sphinx_autodoc_typehints
  - black=19.10b0
  - codecov
  - pytest
  - pytest-cov
  - ezdxf
  - ipython
  - typing_extensions
  - nptyping
  - scipy
  - pip
  - pip:
    - "--editable=."
    - sphinxcadquery
