name: cadquery
channels:
  - cadquery
  - conda-forge
dependencies:
  - python>=3.8
  - sphinx=5.0.1
  - sphinx_rtd_theme
  - pip
  - pip:
    - git+https://github.com/CadQuery/cadquery.git@master
    - git+https://github.com/CadQuery/OCP-stubs.git
